"""add fulltext index and created_at index

Revision ID: 60e0cba37617
Revises: 22618bf62ff3
Create Date: 2026-09-01 19:27:33.743255
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "60e0cba37617"
down_revision: Union[str, None] = "22618bf62ff3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_articles_created", "articles", ["created_at"], unique=False)
    op.create_index("ix_ft_title_content", "articles", ["title", "content"], unique=False, mysql_prefix="FULLTEXT")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ft_title_content", table_name="articles", mysql_prefix="FULLTEXT")
    op.drop_index("ix_articles_created", table_name="articles")
    # ### end Alembic commands ###
