"""add_ad_slots_and_ad_stats

Revision ID: c0e229f6eb36
Revises: 4b3ef358de23
Create Date: 2026-09-01 22:21:31.414571
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "c0e229f6eb36"
down_revision: Union[str, None] = "4b3ef358de23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_slots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("position", sa.String(length=20), nullable=False),
        sa.Column("ad_type", sa.String(length=20), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ad_slots_position"), "ad_slots", ["position"], unique=False)
    op.create_index("ix_ad_slots_position_status", "ad_slots", ["position", "status"], unique=False)
    op.create_index(op.f("ix_ad_slots_status"), "ad_slots", ["status"], unique=False)
    op.create_table(
        "ad_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slot_id", sa.Integer(), nullable=False),
        sa.Column("event", sa.String(length=20), nullable=False),
        sa.Column("date", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(["slot_id"], ["ad_slots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ad_stats_date"), "ad_stats", ["date"], unique=False)
    op.create_index("ix_ad_stats_slot_date", "ad_stats", ["slot_id", "date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ad_stats_slot_date", table_name="ad_stats")
    op.drop_index(op.f("ix_ad_stats_date"), table_name="ad_stats")
    op.drop_table("ad_stats")
    op.drop_index(op.f("ix_ad_slots_status"), table_name="ad_slots")
    op.drop_index("ix_ad_slots_position_status", table_name="ad_slots")
    op.drop_index(op.f("ix_ad_slots_position"), table_name="ad_slots")
    op.drop_table("ad_slots")
    # ### end Alembic commands ###
